# fly.toml file generated for duminingbot on 2022-11-22T15:31:53Z

app = "duminingbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
